version: "3.8"

services:
  digital-twin:
    build:
      context: ./digital-twin
      dockerfile: Dockerfile
    container_name: ev_digital_twin
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ev_frontend_hmi
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - digital-twin
